package se.bergqvist.corleonecontrolpanel;

import se.bergqvist.turntable.Turntable;

/**
 *
 * @author Daniel Bergqvist
 */
public class TurntableFrame extends javax.swing.JFrame
        implements Turntable.TurntableListener {

    /**
     * Creates new form Turntable
     */
    public TurntableFrame() {
        initComponents();

        Turntable.get().addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Track1head = new javax.swing.JButton();
        jButton_Track2head = new javax.swing.JButton();
        jButton_Track1tail = new javax.swing.JButton();
        jButton_Track2tail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Speed = new javax.swing.JTextField();
        jTextField_Direction = new javax.swing.JTextField();
        jTextField_Position = new javax.swing.JTextField();
        jTextField_Track = new javax.swing.JTextField();
        jTextField_Head = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Track1head.setText("Track 1 head");
        jButton_Track1head.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Track1headActionPerformed(evt);
            }
        });

        jButton_Track2head.setText("Track 2 head");
        jButton_Track2head.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Track2headActionPerformed(evt);
            }
        });

        jButton_Track1tail.setText("Track 1 tail");
        jButton_Track1tail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Track1tailActionPerformed(evt);
            }
        });

        jButton_Track2tail.setText("Track 2 tail");
        jButton_Track2tail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Track2tailActionPerformed(evt);
            }
        });

        jLabel2.setText("Position");

        jLabel3.setText("Speed");

        jLabel4.setText("Direction");

        jLabel5.setText("Track");

        jLabel6.setText("Head");

        jTextField_Speed.setText("jTextField1");

        jTextField_Direction.setColumns(20);
        jTextField_Direction.setText("jTextField2");

        jTextField_Position.setText("jTextField3");

        jTextField_Track.setText("jTextField4");

        jTextField_Head.setText("jTextField5");

        jButton1.setText("A");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("B");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Track2head)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Track2tail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Track1head)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Track1tail))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Track, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(260, 260, 260)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Track1head)
                    .addComponent(jButton_Track1tail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Track2head)
                    .addComponent(jButton_Track2tail))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_Track, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Track1headActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Track1headActionPerformed
        Turntable.get().gotoTrack(1, true);
    }//GEN-LAST:event_jButton_Track1headActionPerformed

    private void jButton_Track1tailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Track1tailActionPerformed
        Turntable.get().gotoTrack(1, false);
    }//GEN-LAST:event_jButton_Track1tailActionPerformed

    private void jButton_Track2headActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Track2headActionPerformed
        Turntable.get().gotoTrack(2, true);
    }//GEN-LAST:event_jButton_Track2headActionPerformed

    private void jButton_Track2tailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Track2tailActionPerformed
        Turntable.get().gotoTrack(2, false);
    }//GEN-LAST:event_jButton_Track2tailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Turntable.get().gotoPosition(45878);
//        Turntable.get().gotoPosition(20421);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        Turntable.get().gotoPosition(47238);
        Turntable.get().gotoPosition(47150);
//        Turntable.get().gotoPosition(47170);
//        Turntable.get().gotoPosition(19121);
//        Turntable.get().gotoPosition(19171);
//        Turntable.get().gotoPosition(19221);
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void info(int speed, boolean direction, int pos, int track, boolean head) {
        jTextField_Speed.setText(Integer.toString(speed));
        jTextField_Direction.setText(direction ? "Clock wise" : "Counter clockwise");
        jTextField_Position.setText(Integer.toString(pos));
        jTextField_Track.setText(Integer.toString(track));
        jTextField_Head.setText(head ? "Head" : "Tail");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Track1head;
    private javax.swing.JButton jButton_Track1tail;
    private javax.swing.JButton jButton_Track2head;
    private javax.swing.JButton jButton_Track2tail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_Direction;
    private javax.swing.JTextField jTextField_Head;
    private javax.swing.JTextField jTextField_Position;
    private javax.swing.JTextField jTextField_Speed;
    private javax.swing.JTextField jTextField_Track;
    // End of variables declaration//GEN-END:variables

}
